spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 4592
#    url: jdbc:h2:tcp://localhost/~/e-commerce
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace


port-one-api:
  auth:
    token: "jJuucB7xOS9eivGl87yUTLzQpBONMhMuXZ6t2SByd2CH4FXQDYBvbnfqMOcQu8LSNoVib9JMCyqsrcY7"

